import chainConfig from "./chainType";

export const JAM_TEST_VECTORS = 'external/jam-test-vectors';  
export { CHAIN_TYPE } from "./chainType";

export const {
    VALIDATOR_COUNT,
    CORES_COUNT,
    BITFIELD_LENGTH,
    EPOCH_LENGTH,
    MAX_TICKET_PER_BLOCK,
    TICKETS_PER_VALIDATOR,
    MAX_BLOCKS_HISTORY,
    TIMESLOT_DELAY_PERIOD,
    AUTH_QUEUE_SIZE,
    AUTH_POOL_MAX_SIZE,
    TOTAL_ACCUMULATE_GAS,
    MAX_WORK_SIZE,
    TIMEOUT,
    ROTATION_PERIOD,
    MAX_AGE_IN_TIMESLOTS,
    PEAK_PREFIX,
    VALIDATORS_PER_CORE,
    VOTE_COUNT,
    CONTEST_DURATION,
    VALIDATOR_SUPERMAJORITY,
    TOTAL_GAS_FOR_ALL_ACCUMULATION,
    TOTAL_GAS_FOR_WORK_PACKAGE_REFINE_LOGIC,
    TOTAL_GAS_FOR_WORK_PACKAGE_IS_AUTHORIZED_LOGIC,
    MAX_EXTRINSICS_IN_WORK_PACKAGE,
    MAX_IMPORTS_EXPORTS_IN_WORK_PACKAGE,
    PERIOD_FOR_EXPUNGING_PREIMAGES,
   
   
  } = chainConfig;



